vich_uploader:
    db_driver: orm

    mappings:
        img:
            uri_prefix: /uploads/img
            upload_destination: '%kernel.project_dir%/public/uploads/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
